name: Run All Python Scripts Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-all-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver_manager
    
    - name: Create credentials file
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Run all scripts
      run: |
        python titulares.py
        python resulale.py
        python Sacaresultadosmadridfut.py
        python resulben.py
        python resulcad.py
        python resulinfan.py
        python resultjunior.py
        python Sacaresultadosracing.py
        python sacaresultadosmadridbas.py
