name: Run Python Scripts

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # titulares.py: Every hour except between 2 AM and 5 AM
    - cron: '0 0-1,6-23 * * *'
    # Sacaresultados scripts: 3 PM daily
    - cron: '0 15 * * *'
    # Sacaresultados scripts: 6 PM daily
    - cron: '0 18 * * *'
    # Sacaresultados scripts: 9 PM daily
    - cron: '0 21 * * *'
    # Sacaresultados scripts: 12 AM daily
    - cron: '0 0 * * *'
    # Weekend scripts: Saturday 1 PM
    - cron: '0 13 * * 6'
    # Weekend scripts: Saturday 4 PM
    - cron: '0 16 * * 6'
    # Weekend scripts: Saturday 9 PM
    - cron: '0 21 * * 6'
    # Weekend scripts: Sunday 1 PM
    - cron: '0 13 * * 0'
    # Weekend scripts: Sunday 4 PM
    - cron: '0 16 * * 0'
    # Weekend scripts: Sunday 9 PM
    - cron: '0 21 * * 0'

jobs:
  # Job for titulares.py
  run-titulares:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run titulares.py
        run: python titulares.py

  # Job for Sacaresultados scripts
  run-sacaresultados:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run Sacaresultados scripts
        run: |
          python Sacaresultadosmadridfut.py
          python Sacaresultadosracing.py
          python sacaresultadosmadridbas.py

  # Job for weekend scripts
  run-weekend-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run weekend scripts
        run: |
          python resulben.py
          python resulale.py
          python resulinfan.py
          python resulcad.py
          python resultjunior.py
