name: Run Python Scripts

on:
  schedule:
    - cron: '0 * * * *'  # Every hour for titulares.py
    - cron: '0 15,18,21 * * *'  # Every day at 3pm, 6pm, 9pm
    - cron: '30 23 * * *'  # Every day at 11:30pm
    - cron: '0 15,22 * * 3,6,0'  # Wed, Sat, Sun at 3pm and 10pm
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-titulares:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install titulares dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_titulares.txt
    - name: Create credentials file
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    - name: Run titulares script
      run: python titulares.py

  run-daily-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install common dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_common.txt
    - name: Create credentials file
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    - name: Run daily scripts
      run: |
        if [[ $(date +%H:%M) == "15:00" || $(date +%H:%M) == "18:00" || $(date +%H:%M) == "21:00" || $(date +%H:%M) == "23:30" ]]; then
          python sacaresultadosmadridbas.py
          python Sacaresultadosracing.py
          python Sacaresultadosmadridfut.py
        fi

  run-weekly-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install common dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_common.txt
    - name: Create credentials file
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    - name: Run weekly scripts
      run: |
        if [[ $(date +%u) == 3 || $(date +%u) == 6 || $(date +%u) == 0 ]] && [[ $(date +%H:%M) == "15:00" || $(date +%H:%M) == "22:00" ]]; then
          python resulale.py
          python resulben.py
          python resulcad.py
          python resulinfan.py
          python resultjunior.py
        fi
