name: Ejecutar titulares.py cada hora

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora (UTC)
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client beautifulsoup4 requests

    - name: Crear archivo de credenciales
      run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

    - name: Ejecutar script
      run: python titulares.py
